/* DSblock model generated by Dymola from Modelica model WasteWater.ASM1.sensor_EQ
 Dymola Version 2014 FD01 (32-bit), 2013-10-17 translated this at Sat Feb 24 17:41:53 2018

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
DYMOLA_STATIC const char*modelName="WasteWater.ASM1.sensor_EQ";
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/fahdb/appdata/roaming/dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[0] = 0.0;
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("In.Q", "[m3/d]", 0.0, 0.0,0.0,0.0,0,777)
DeclareParameter("Bss", "", 0, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("Bcod", "", 1, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("Bnkj", "", 2, 30, 0.0,0.0,0.0,0,560)
DeclareParameter("Bno", "", 3, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("Bbod5", "", 4, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("iXB", "", 5, 0.08, 0.0,0.0,0.0,0,560)
DeclareParameter("iXP", "", 6, 0.06, 0.0,0.0,0.0,0,560)
DeclareParameter("fp", "", 7, 0.08, 0.0,0.0,0.0,0,560)
DeclareParameter("Xxa", "", 8, 0.09, 0.0,0.0,0.0,0,560)
EndNonAlias(0)
#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    1
#define NP_    9
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -270715430
#define NHash2_ 1190021505
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
