/* DSblock model generated by Dymola from Modelica model WasteWater.ASM1.sensor_PE
 Dymola Version 2014 FD01 (32-bit), 2013-10-17 translated this at Tue Feb 20 11:50:45 2018

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
DYMOLA_STATIC const char*modelName="WasteWater.ASM1.sensor_PE";
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/simenrau/appdata/roaming/dynasim/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC long QJacobianCG_[4]={1 , 2 , 1 , 2};
DYMOLA_STATIC long QJacobianGC_[3]={
2 , 0 , 0};
DYMOLA_STATIC double QJacobianCD_[3]={0  , 44 , 55};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
F_[1] = 1.0;
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
F_[1] = 1.0;
F_[0] = divmacro(241.2583292,"241.2583292",X_[1],"T");

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareInput("Kla3", "[:#(prefix=input)]", 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("Kla4", "[:#(prefix=input)]", 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("Kla5", "[:#(prefix=input)]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("PE", "", 0, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(PE)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("T", "", 1, 0.001, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(T)", "", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)
#define NX_    2
#define NX2_   0
#define NU_    3
#define NY_    0
#define NW_    0
#define NP_    0
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1449062937
#define NHash2_ 1900640568
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
